package greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import greendao.Config;
import greendao.Device;
import greendao.Message;

import greendao.ConfigDao;
import greendao.DeviceDao;
import greendao.MessageDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig configDaoConfig;
    private final DaoConfig deviceDaoConfig;
    private final DaoConfig messageDaoConfig;

    private final ConfigDao configDao;
    private final DeviceDao deviceDao;
    private final MessageDao messageDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        configDaoConfig = daoConfigMap.get(ConfigDao.class).clone();
        configDaoConfig.initIdentityScope(type);

        deviceDaoConfig = daoConfigMap.get(DeviceDao.class).clone();
        deviceDaoConfig.initIdentityScope(type);

        messageDaoConfig = daoConfigMap.get(MessageDao.class).clone();
        messageDaoConfig.initIdentityScope(type);

        configDao = new ConfigDao(configDaoConfig, this);
        deviceDao = new DeviceDao(deviceDaoConfig, this);
        messageDao = new MessageDao(messageDaoConfig, this);

        registerDao(Config.class, configDao);
        registerDao(Device.class, deviceDao);
        registerDao(Message.class, messageDao);
    }
    
    public void clear() {
        configDaoConfig.getIdentityScope().clear();
        deviceDaoConfig.getIdentityScope().clear();
        messageDaoConfig.getIdentityScope().clear();
    }

    public ConfigDao getConfigDao() {
        return configDao;
    }

    public DeviceDao getDeviceDao() {
        return deviceDao;
    }

    public MessageDao getMessageDao() {
        return messageDao;
    }

}
