package greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here

import android.database.Cursor;

import org.joda.time.DateTime;

import java.util.Date;

import eu.codlab.cypherx.ApplicationController;
import eu.codlab.cypherx.R;
import eu.codlab.cypherx.ui.messages.MessageConstants;
// KEEP INCLUDES END

/**
 * Entity mapped to table MESSAGE.
 */
public class Message {

    private Long id;
    /**
     * Not-null value.
     */
    private String device_guid;
    /**
     * Not-null value.
     */
    private String encrypted_content;
    private String encrypted_content_local;
    /**
     * Not-null value.
     */
    private java.util.Date received_at;
    private int type;
    private String signature;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Message() {
    }

    public Message(Long id) {
        this.id = id;
    }

    public Message(Long id, String device_guid, String encrypted_content, String encrypted_content_local, java.util.Date received_at, int type, String signature) {
        this.id = id;
        this.device_guid = device_guid;
        this.encrypted_content = encrypted_content;
        this.encrypted_content_local = encrypted_content_local;
        this.received_at = received_at;
        this.type = type;
        this.signature = signature;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /**
     * Not-null value.
     */
    public String getDevice_guid() {
        return device_guid;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setDevice_guid(String device_guid) {
        this.device_guid = device_guid;
    }

    /**
     * Not-null value.
     */
    public String getEncrypted_content() {
        return encrypted_content;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setEncrypted_content(String encrypted_content) {
        this.encrypted_content = encrypted_content;
    }

    public String getEncrypted_content_local() {
        return encrypted_content_local;
    }

    public void setEncrypted_content_local(String encrypted_content_local) {
        this.encrypted_content_local = encrypted_content_local;
    }

    /**
     * Not-null value.
     */
    public java.util.Date getReceived_at() {
        return received_at;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setReceived_at(java.util.Date received_at) {
        this.received_at = received_at;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public String getSignature() {
        return signature;
    }

    public void setSignature(String signature) {
        this.signature = signature;
    }

    // KEEP METHODS - put your custom methods here
    public String getStatusMessage() {
        int res = R.string.sending;
        switch (getType()) {
            case MessageConstants.SENDING:
                res = R.string.sending;
                break;
            case MessageConstants.NOT_SENT:
                res = R.string.not_sent;
                break;
            case MessageConstants.RECEIVED:
                res = R.string.received;
                break;
            case MessageConstants.SENT:
                res = R.string.sent;
                break;
        }
        return ApplicationController.getInstance().getString(res);
    }

    public String getStatusDateMessage() {
        DateTime date = new DateTime(getReceived_at());
        return String.format("%s %02d/%02d/%04d",
                getStatusMessage(),
                date.getDayOfMonth(),
                date.getMonthOfYear(),
                date.getYear());
    }

    public static Message fromCursor(Cursor cursor) {
        Message message = new Message();

        int column_id_db = cursor.getColumnIndex(MessageDao.Properties.Id.columnName);
        int column_index = cursor.getColumnIndex(MessageDao.Properties.Encrypted_content.columnName);
        int colom_local_index = cursor.getColumnIndex(MessageDao.Properties
                .Encrypted_content_local.columnName);
        int guid_index = cursor.getColumnIndex(MessageDao.Properties
                .Device_guid.columnName);
        int received_index = cursor.getColumnIndex(MessageDao.Properties
                .Received_at.columnName);
        int type_index = cursor.getColumnIndex(MessageDao.Properties
                .Type.columnName);

        message.setId(cursor.getLong(column_id_db));
        message.setEncrypted_content(cursor.getString(column_index));
        message.setEncrypted_content_local(cursor.getString(colom_local_index));
        message.setType(cursor.getInt(type_index));
        message.setReceived_at(new Date(cursor.getLong(received_index)));
        message.setDevice_guid(cursor.getString(guid_index));

        return message;
    }
    // KEEP METHODS END

}
